<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_UgTbgCX3EeiUP84-WOsXNQ" name="test" author="Victor" bonitaVersion="7.7.0" bonitaModelVersion="7.6.0-002" configId="ACED000574001474657374372E362E302D303032372E372E307370">
    <elements xmi:type="process:Pool" xmi:id="_UgTbgSX3EeiUP84-WOsXNQ" name="test" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_UgTbgiX3EeiUP84-WOsXNQ" name="Employee lane" actor="_UgUppSX3EeiUP84-WOsXNQ">
        <elements xmi:type="process:StartEvent" xmi:id="_UgTbgyX3EeiUP84-WOsXNQ" name="Start1" outgoing="_UgUpoiX3EeiUP84-WOsXNQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_UgTbhCX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UgTbhSX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UgTbhiX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UgTbhyX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UgTbiCX3EeiUP84-WOsXNQ" name="Step1" incoming="_UgUpoiX3EeiUP84-WOsXNQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_UgTbiSX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UgTbiiX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UgTbiyX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UgTbjCX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UgTbjSX3EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UgTbjiX3EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UgTbjyX3EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UgTbkCX3EeiUP84-WOsXNQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UgTbkSX3EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_UgTbkiX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_UgTbkyX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_UgTblCX3EeiUP84-WOsXNQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_UgTblSX3EeiUP84-WOsXNQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UgTbliX3EeiUP84-WOsXNQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_UgTblyX3EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_UrbtcCX3EeiUP84-WOsXNQ" path="_UgTbgSX3EeiUP84-WOsXNQ/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_UgTbmSX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_UgTbmiX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_UgTbmyX3EeiUP84-WOsXNQ" path="_PeiKwSX3EeiUP84-WOsXNQ/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_UgUCkCX3EeiUP84-WOsXNQ" path="_UgTbgSX3EeiUP84-WOsXNQ/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_UgUCkSX3EeiUP84-WOsXNQ" path="_UgTbgSX3EeiUP84-WOsXNQ/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_UgUCkiX3EeiUP84-WOsXNQ" path="_UgTbgSX3EeiUP84-WOsXNQ/html/consultation.html"/>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_UgUCkyX3EeiUP84-WOsXNQ" path="_UgTbgSX3EeiUP84-WOsXNQ/html/_UgTbgSX3EeiUP84-WOsXNQconfirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_UgUClCX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_UgUClSX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_UgUCliX3EeiUP84-WOsXNQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_XfvoICX3EeiUP84-WOsXNQ" name="newForm" content="2efad7ec-da12-4ec5-b0cf-0def11b984ef" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_UgUCmCX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_UgUCmSX3EeiUP84-WOsXNQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_UgUpoCX3EeiUP84-WOsXNQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_UgUpoSX3EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UgUpoiX3EeiUP84-WOsXNQ" target="_UgTbiCX3EeiUP84-WOsXNQ" source="_UgTbgyX3EeiUP84-WOsXNQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UgUpoyX3EeiUP84-WOsXNQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_UgUppCX3EeiUP84-WOsXNQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_UgUppSX3EeiUP84-WOsXNQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_UgUppiX3EeiUP84-WOsXNQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_WqaioCX3EeiUP84-WOsXNQ" name="input1">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_WqaioSX3EeiUP84-WOsXNQ"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_UgUppyX3EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_UgUpqCX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_UgUpqSX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_UgUpqiX3EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_UgUpqyX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_UgUprCX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_UgUprSX3EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_UgUpriX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_UgUpryX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_UgUpsCX3EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_UgUpsSX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_UgUpsiX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_UgUpsyX3EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_UgUptCX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_UgUptSX3EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_UgUptiX3EeiUP84-WOsXNQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_UgUptyX3EeiUP84-WOsXNQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_UgUpuCX3EeiUP84-WOsXNQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_UgUpuSX3EeiUP84-WOsXNQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_UgUpuiX3EeiUP84-WOsXNQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_UgUpuyX3EeiUP84-WOsXNQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_UgUpvCX3EeiUP84-WOsXNQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_UgUpvSX3EeiUP84-WOsXNQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_UgUpviX3EeiUP84-WOsXNQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_UgUpvyX3EeiUP84-WOsXNQ" type="Process" element="_UgTbgCX3EeiUP84-WOsXNQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_UgUpwCX3EeiUP84-WOsXNQ" type="2007" element="_UgTbgSX3EeiUP84-WOsXNQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_UgUpwSX3EeiUP84-WOsXNQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_UgUpwiX3EeiUP84-WOsXNQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_UgUpwyX3EeiUP84-WOsXNQ" type="3007" element="_UgTbgiX3EeiUP84-WOsXNQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_UgUpxCX3EeiUP84-WOsXNQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_UgUpxSX3EeiUP84-WOsXNQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_UgUpxiX3EeiUP84-WOsXNQ" type="3005" element="_UgTbiCX3EeiUP84-WOsXNQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UgUpxyX3EeiUP84-WOsXNQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UgUpyCX3EeiUP84-WOsXNQ" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UgUpySX3EeiUP84-WOsXNQ" type="3002" element="_UgTbgyX3EeiUP84-WOsXNQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_UgUpyiX3EeiUP84-WOsXNQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_UgUpyyX3EeiUP84-WOsXNQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UgUpzCX3EeiUP84-WOsXNQ" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_UgUpzSX3EeiUP84-WOsXNQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_UgUpziX3EeiUP84-WOsXNQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_UgUpzyX3EeiUP84-WOsXNQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_UgUp0CX3EeiUP84-WOsXNQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UgUp0SX3EeiUP84-WOsXNQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_UgUp0iX3EeiUP84-WOsXNQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_UgUp0yX3EeiUP84-WOsXNQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_UgUp1CX3EeiUP84-WOsXNQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_UgUp1SX3EeiUP84-WOsXNQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UgUp1iX3EeiUP84-WOsXNQ" width="1680" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_UgUp1yX3EeiUP84-WOsXNQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_UgUp2CX3EeiUP84-WOsXNQ" type="4001" element="_UgUpoiX3EeiUP84-WOsXNQ" source="_UgUpySX3EeiUP84-WOsXNQ" target="_UgUpxiX3EeiUP84-WOsXNQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UgUp2SX3EeiUP84-WOsXNQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UgUp2iX3EeiUP84-WOsXNQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UgUp2yX3EeiUP84-WOsXNQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UgUp3CX3EeiUP84-WOsXNQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
