<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_ova40CX6EeiUP84-WOsXNQ" name="test" version="2.0" author="Victor" bonitaVersion="7.7.0" bonitaModelVersion="7.6.0-002" configId="ACED000574001474657374372E362E302D303032372E372E307370">
    <elements xmi:type="process:Pool" xmi:id="_ova40SX6EeiUP84-WOsXNQ" name="test" welcomePageInternal="false" basedOnLookAndFeel="Default Application" version="2.0">
      <elements xmi:type="process:Lane" xmi:id="_ova40iX6EeiUP84-WOsXNQ" name="Employee lane" actor="_ova4-yX6EeiUP84-WOsXNQ">
        <elements xmi:type="process:StartEvent" xmi:id="_ova40yX6EeiUP84-WOsXNQ" name="Start1" outgoing="_ova4-CX6EeiUP84-WOsXNQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ova41CX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ova41SX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ova41iX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ova41yX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_ova42CX6EeiUP84-WOsXNQ" name="Step1" incoming="_ova4-CX6EeiUP84-WOsXNQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ova42SX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ova42iX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ova42yX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ova43CX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ova43SX6EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ova43iX6EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ova43yX6EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ova44CX6EeiUP84-WOsXNQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ova44SX6EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_ova44iX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_ova44yX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ova45CX6EeiUP84-WOsXNQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_ova45SX6EeiUP84-WOsXNQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ova45iX6EeiUP84-WOsXNQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ova45yX6EeiUP84-WOsXNQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_qSz-MCX6EeiUP84-WOsXNQ" path="_ova40SX6EeiUP84-WOsXNQ/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_ova46SX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_ova46iX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_ova46yX6EeiUP84-WOsXNQ" path="_PeiKwSX3EeiUP84-WOsXNQ/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_ova47CX6EeiUP84-WOsXNQ" path="_ova40SX6EeiUP84-WOsXNQ/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_ova47SX6EeiUP84-WOsXNQ" path="_ova40SX6EeiUP84-WOsXNQ/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_ova47iX6EeiUP84-WOsXNQ" path="_ova40SX6EeiUP84-WOsXNQ/html/consultation.html"/>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_ova47yX6EeiUP84-WOsXNQ" path="_ova40SX6EeiUP84-WOsXNQ/html/_ova40SX6EeiUP84-WOsXNQconfirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_ova48CX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_ova48SX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ova48iX6EeiUP84-WOsXNQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ova48yX6EeiUP84-WOsXNQ" name="newForm" content="2efad7ec-da12-4ec5-b0cf-0def11b984ef" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ova49CX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ova49SX6EeiUP84-WOsXNQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ova49iX6EeiUP84-WOsXNQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ova49yX6EeiUP84-WOsXNQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ova4-CX6EeiUP84-WOsXNQ" target="_ova42CX6EeiUP84-WOsXNQ" source="_ova40yX6EeiUP84-WOsXNQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ova4-SX6EeiUP84-WOsXNQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ova4-iX6EeiUP84-WOsXNQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_ova4-yX6EeiUP84-WOsXNQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_ova4_CX6EeiUP84-WOsXNQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_ova4_SX6EeiUP84-WOsXNQ" name="input1">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_ova4_iX6EeiUP84-WOsXNQ"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ova4_yX6EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_ova5ACX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ova5ASX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ova5AiX6EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_ova5AyX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ova5BCX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ova5BSX6EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_ova5BiX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ova5ByX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ova5CCX6EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_ova5CSX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ova5CiX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ova5CyX6EeiUP84-WOsXNQ">
        <name xmi:type="expression:Expression" xmi:id="_ova5DCX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ova5DSX6EeiUP84-WOsXNQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_ova5DiX6EeiUP84-WOsXNQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_ova5DyX6EeiUP84-WOsXNQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_ova5ECX6EeiUP84-WOsXNQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_ova5ESX6EeiUP84-WOsXNQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_ova5EiX6EeiUP84-WOsXNQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_ova5EyX6EeiUP84-WOsXNQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_ova5FCX6EeiUP84-WOsXNQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_ova5FSX6EeiUP84-WOsXNQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_ova5FiX6EeiUP84-WOsXNQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_ova5FyX6EeiUP84-WOsXNQ" type="Process" element="_ova40CX6EeiUP84-WOsXNQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_ova5GCX6EeiUP84-WOsXNQ" type="2007" element="_ova40SX6EeiUP84-WOsXNQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_ova5GSX6EeiUP84-WOsXNQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ova5GiX6EeiUP84-WOsXNQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_ova5GyX6EeiUP84-WOsXNQ" type="3007" element="_ova40iX6EeiUP84-WOsXNQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_ova5HCX6EeiUP84-WOsXNQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_ova5HSX6EeiUP84-WOsXNQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ova5HiX6EeiUP84-WOsXNQ" type="3005" element="_ova42CX6EeiUP84-WOsXNQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ova5HyX6EeiUP84-WOsXNQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ova5ICX6EeiUP84-WOsXNQ" x="160" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ova5ISX6EeiUP84-WOsXNQ" type="3002" element="_ova40yX6EeiUP84-WOsXNQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ova5IiX6EeiUP84-WOsXNQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ova5IyX6EeiUP84-WOsXNQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ova5JCX6EeiUP84-WOsXNQ" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_ova5JSX6EeiUP84-WOsXNQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_ova5JiX6EeiUP84-WOsXNQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_ova5JyX6EeiUP84-WOsXNQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_ova5KCX6EeiUP84-WOsXNQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ova5KSX6EeiUP84-WOsXNQ"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ova5KiX6EeiUP84-WOsXNQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ova5KyX6EeiUP84-WOsXNQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ova5LCX6EeiUP84-WOsXNQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ova5LSX6EeiUP84-WOsXNQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ova5LiX6EeiUP84-WOsXNQ" width="1680" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_ova5LyX6EeiUP84-WOsXNQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_ova5MCX6EeiUP84-WOsXNQ" type="4001" element="_ova4-CX6EeiUP84-WOsXNQ" source="_ova5ISX6EeiUP84-WOsXNQ" target="_ova5HiX6EeiUP84-WOsXNQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ova5MSX6EeiUP84-WOsXNQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ova5MiX6EeiUP84-WOsXNQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ova5MyX6EeiUP84-WOsXNQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ova5NCX6EeiUP84-WOsXNQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
